In [1]:
import pandas as pd
import numpy as np

# Warped data process

In [2]:
data = pd.read_csv("row_data/data_more_drastic.csv", header=None)
# delete NaNs
clean_data = data.dropna()
data = clean_data.values
data.shape
data_df = pd.DataFrame(data)
data_df

,0,1,2,3,4,5,6,7,8,9,...,991,992,993,994,995,996,997,998,999,1000
0,0.001092,0.001855,0.003398,0.003021,0.001142,0.001162,0.001791,0.001056,0.001989,0.003067,...,0.012576,0.012221,0.010489,0.008609,0.008218,0.007042,0.005879,0.004581,0.005354,0.0
1,0.000484,0.001168,0.002622,0.002147,0.000159,0.000058,0.000552,-0.000332,0.000436,0.001332,...,0.020808,0.020305,0.018430,0.016407,0.015876,0.014563,0.013265,0.011835,0.012476,0.0
2,0.001742,0.002584,0.004213,0.003932,0.002160,0.002296,0.003053,0.002459,0.003547,0.004795,...,0.014226,0.013842,0.012081,0.010173,0.009754,0.008552,0.007362,0.006038,0.006785,0.0
3,0.000087,0.000718,0.002115,0.001574,-0.000486,-0.000668,-0.000265,-0.001248,-0.000591,0.000183,...,0.012576,0.012221,0.010488,0.008608,0.008216,0.007040,0.005877,0.004578,0.005351,0.0
4,0.000128,0.000765,0.002169,0.001636,-0.000415,-0.000587,-0.000171,-0.001142,-0.000469,0.000322,...,0.019380,0.018905,0.017057,0.015061,0.014556,0.013270,0.011997,0.010591,0.011257,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,0.003737,0.004334,0.005669,0.005045,0.002872,0.002543,0.002765,0.001553,0.001939,0.002383,...,0.224991,0.213285,0.200705,0.188472,0.178200,0.167601,0.157456,0.147597,0.140222,1.0
5996,0.007266,0.007955,0.009382,0.008853,0.006776,0.006545,0.006869,0.005760,0.006254,0.006806,...,0.256466,0.243122,0.228977,0.215249,0.203550,0.191589,0.180146,0.169049,0.160495,1.0
5997,0.006572,0.007240,0.008647,0.008097,0.005999,0.005747,0.006048,0.004915,0.005385,0.005913,...,0.172021,0.162342,0.151740,0.141436,0.133043,0.124273,0.115907,0.107778,0.102082,1.0
5998,0.016728,0.017638,0.019287,0.018988,0.017145,0.017153,0.017723,0.016860,0.017613,0.018423,...,0.162727,0.153385,0.143114,0.133134,0.125060,0.116602,0.108542,0.100710,0.095306,1.0
5999,0.009440,0.010180,0.011659,0.011184,0.009161,0.008986,0.009368,0.008316,0.008870,0.009482,...,0.238503,0.226079,0.212813,0.199925,0.189029,0.177836,0.167124,0.156726,0.148838,1.0

In [3]:
num_data = data.shape[0]
np.random.seed(3407)
_new_order = list(range(num_data))
np.random.shuffle(_new_order)
data = data[_new_order, :]
data_df = pd.DataFrame(data)
data_df

,0,1,2,3,4,5,6,7,8,9,...,991,992,993,994,995,996,997,998,999,1000
0,0.018488,0.019898,0.022089,0.022357,0.021117,0.021765,0.023006,0.022869,0.024378,0.026000,...,0.235975,0.228303,0.219452,0.210674,0.203583,0.195897,0.188409,0.180963,0.175769,1.0
1,0.001081,0.001628,0.002917,0.002243,0.000022,-0.000356,-0.000184,-0.001441,-0.001106,-0.000707,...,0.020450,0.019067,0.016370,0.013603,0.012383,0.010446,0.008575,0.006627,0.006798,0.0
2,0.000100,0.000593,0.001824,0.001091,-0.001194,-0.001635,-0.001532,-0.002861,-0.002602,-0.002282,...,0.020978,0.019285,0.016319,0.013313,0.011895,0.009785,0.007772,0.005699,0.005773,0.0
3,0.001898,0.002644,0.004153,0.003726,0.001779,0.001703,0.002213,0.001326,0.002070,0.002919,...,0.019792,0.019097,0.017031,0.014838,0.014139,0.012667,0.011224,0.009651,0.010160,0.0
4,0.005726,0.007007,0.009116,0.009357,0.008158,0.008924,0.010364,0.010511,0.012416,0.014548,...,0.156032,0.153610,0.149819,0.145927,0.143533,0.140402,0.137290,0.134090,0.132967,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,0.010055,0.011148,0.013014,0.012949,0.011369,0.011669,0.012553,0.012046,0.013171,0.014401,...,0.196953,0.190766,0.183356,0.175957,0.170197,0.163803,0.157567,0.151336,0.147319,1.0
5996,0.006582,0.007764,0.009742,0.009824,0.008428,0.008946,0.010103,0.009909,0.011404,0.013064,...,0.129313,0.126493,0.122337,0.118098,0.115381,0.111920,0.108536,0.105046,0.103666,1.0
5997,0.001038,0.001574,0.002850,0.002164,-0.000072,-0.000464,-0.000306,-0.001582,-0.001263,-0.000884,...,0.026220,0.024376,0.021261,0.018094,0.016515,0.014236,0.012053,0.009812,0.009714,0.0
5998,0.017603,0.019046,0.021277,0.021592,0.020406,0.021116,0.022426,0.022362,0.023947,0.025654,...,0.147130,0.142291,0.136198,0.130088,0.125590,0.120428,0.115398,0.110345,0.107480,1.0
5999,0.004181,0.005259,0.007142,0.007132,0.005655,0.006103,0.007200,0.006968,0.008437,0.010101,...,0.157162,0.154464,0.150440,0.146292,0.143672,0.140301,0.136971,0.133549,0.132214,1.0

In [4]:
class_0_data_df = data_df[data_df.iloc[:, -1] == 0]
class_1_data_df = data_df[data_df.iloc[:, -1] == 1]

In [5]:
print(f"In total we have {num_data} examples")
test_n = 4000

In total we have 6000 examples

# True data

In [6]:
data_true = pd.read_csv("row_data/allTrueSignals.csv", header=None)
# delete NaNs
clean_data_true = data_true.dropna()
new_column_data = [0.] * 3000 + [1.] * 3000
# 添加新列
clean_data_true['1000'] = new_column_data
data_true = clean_data_true.values
data_true = data_true[_new_order, :]
data_true_df = pd.DataFrame(data_true)
data_true_df

,0,1,2,3,4,5,6,7,8,9,...,991,992,993,994,995,996,997,998,999,1000
0,0.019604,0.020746,0.021949,0.023216,0.024550,0.025954,0.027431,0.028985,0.030619,0.032338,...,0.225366,0.219128,0.213043,0.207107,0.201317,0.195671,0.190165,0.184797,0.179563,1.0
1,0.002197,0.002355,0.002524,0.002703,0.002895,0.003100,0.003318,0.003550,0.003798,0.004062,...,0.015638,0.014903,0.014201,0.013530,0.012888,0.012274,0.011688,0.011127,0.010592,0.0
2,0.001216,0.001310,0.001410,0.001518,0.001633,0.001757,0.001890,0.002032,0.002184,0.002347,...,0.014272,0.013585,0.012928,0.012301,0.011702,0.011130,0.010584,0.010064,0.009567,0.0
3,0.003014,0.003223,0.003446,0.003683,0.003936,0.004204,0.004490,0.004794,0.005117,0.005461,...,0.020395,0.019461,0.018568,0.017712,0.016893,0.016108,0.015358,0.014640,0.013954,0.0
4,0.006842,0.007315,0.007818,0.008353,0.008922,0.009527,0.010170,0.010853,0.011579,0.012349,...,0.172416,0.167551,0.162808,0.158183,0.153676,0.149282,0.145000,0.140827,0.136761,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,0.011171,0.011890,0.012652,0.013460,0.014315,0.015220,0.016178,0.017191,0.018263,0.019396,...,0.190510,0.185135,0.179893,0.174784,0.169803,0.164948,0.160216,0.155606,0.151113,1.0
5996,0.007698,0.008211,0.008756,0.009335,0.009949,0.010600,0.011291,0.012023,0.012799,0.013621,...,0.138116,0.133899,0.129797,0.125808,0.121929,0.118157,0.114490,0.110925,0.107460,1.0
5997,0.002154,0.002308,0.002473,0.002650,0.002838,0.003038,0.003252,0.003480,0.003722,0.003981,...,0.019743,0.018839,0.017974,0.017146,0.016353,0.015594,0.014867,0.014172,0.013508,0.0
5998,0.018718,0.019809,0.020957,0.022167,0.023441,0.024781,0.026192,0.027675,0.029236,0.030877,...,0.142299,0.138040,0.133895,0.129862,0.125937,0.122118,0.118403,0.114789,0.111274,1.0
5999,0.005297,0.005676,0.006080,0.006512,0.006972,0.007462,0.007984,0.008540,0.009132,0.009762,...,0.172259,0.167303,0.162474,0.157768,0.153184,0.148718,0.144369,0.140133,0.136008,1.0

In [7]:
class_0_true_data_df = data_true_df[data_true_df.iloc[:, -1] == 0]
class_1_true_data_df = data_true_df[data_true_df.iloc[:, -1] == 1]

In [8]:
# keep test/valid

# train/valid
split = (4, 1) 
num_tr_val = num_data - test_n
train_n = num_tr_val // sum(split) * split[0]
valid_n = num_tr_val // sum(split) * split[1]

class_0_true_data_df = class_0_true_data_df.values
class_1_true_data_df = class_1_true_data_df.values

# for test and valid, randomly choose test/2 and valid_n/2 from each class to build a balance test/valid set (the rest examples are left for the train set)
n_test_class_0_split = test_n // 2
n_test_class_1_split = test_n - n_test_class_0_split

n_valid_class_0_split = valid_n // 2
n_valid_class_1_split = valid_n - n_valid_class_0_split

raw_data_true_test_0 = pd.DataFrame(class_0_true_data_df[:n_test_class_0_split, :])
raw_data_true_valid_0 = pd.DataFrame(class_0_true_data_df[n_test_class_0_split:(n_test_class_0_split+n_valid_class_0_split), :])
raw_data_true_train_0 = pd.DataFrame(class_0_true_data_df[(n_test_class_0_split+n_valid_class_0_split):, :])

raw_data_true_test_1 = pd.DataFrame(class_1_true_data_df[:n_test_class_1_split, :])
raw_data_true_valid_1 = pd.DataFrame(class_1_true_data_df[n_test_class_1_split:(n_test_class_1_split+n_valid_class_1_split), :])
raw_data_true_train_1 = pd.DataFrame(class_1_true_data_df[(n_test_class_1_split+n_valid_class_1_split):, :])

# merge
raw_data_true_train = pd.concat([raw_data_true_train_0, raw_data_true_train_1])
raw_data_true_valid = pd.concat([raw_data_true_valid_0, raw_data_true_valid_1])
raw_data_true_test = pd.concat([raw_data_true_test_0, raw_data_true_test_1])

len(raw_data_true_train), len(raw_data_true_valid), len(raw_data_true_test)

(1600, 400, 4000)

In [9]:
d_len = data_true_df.shape[1] - 1 # last col
raw_data_true_train[d_len] = raw_data_true_train[d_len].astype(int)
raw_data_true_valid[d_len] = raw_data_true_valid[d_len].astype(int)
raw_data_true_test[d_len] = raw_data_true_test[d_len].astype(int)

In [10]:
case = 'medium'
fo_dir = case + "/"
raw_data_true_train.to_csv(fo_dir + 'train_true.csv', index=False, header=False)
raw_data_true_valid.to_csv(fo_dir + 'valid_true.csv', index=False, header=False)
raw_data_true_test.to_csv(fo_dir + 'test_true.csv', index=False, header=False)

# Split

In [11]:
# keep test/valid

# train/valid
split = (4, 1) 
num_tr_val = num_data - test_n
train_n = num_tr_val // sum(split) * split[0]
valid_n = num_tr_val // sum(split) * split[1]

class_0_data_df = class_0_data_df.values
class_1_data_df = class_1_data_df.values

# for test and valid, randomly choose test/2 and valid_n/2 from each class to build a balance test/valid set (the rest examples are left for the train set)
n_test_class_0_split = test_n // 2
n_test_class_1_split = test_n - n_test_class_0_split

n_valid_class_0_split = valid_n // 2
n_valid_class_1_split = valid_n - n_valid_class_0_split

raw_data_test_0 = pd.DataFrame(class_0_data_df[:n_test_class_0_split, :])
raw_data_valid_0 = pd.DataFrame(class_0_data_df[n_test_class_0_split:(n_test_class_0_split+n_valid_class_0_split), :])
raw_data_train_0 = pd.DataFrame(class_0_data_df[(n_test_class_0_split+n_valid_class_0_split):, :])

raw_data_test_1 = pd.DataFrame(class_1_data_df[:n_test_class_1_split, :])
raw_data_valid_1 = pd.DataFrame(class_1_data_df[n_test_class_1_split:(n_test_class_1_split+n_valid_class_1_split), :])
raw_data_train_1 = pd.DataFrame(class_1_data_df[(n_test_class_1_split+n_valid_class_1_split):, :])

# merge
raw_data_train = pd.concat([raw_data_train_0, raw_data_train_1])
raw_data_valid = pd.concat([raw_data_valid_0, raw_data_valid_1])
raw_data_test = pd.concat([raw_data_test_0, raw_data_test_1])

len(raw_data_train), len(raw_data_valid), len(raw_data_test)

(1600, 400, 4000)

In [12]:
train_n, valid_n, test_n

(1600, 400, 4000)

In [13]:
d_len = data_df.shape[1] - 1 # last col
d_len

1000

In [14]:
raw_data_train[d_len] = raw_data_train[d_len].astype(int)
raw_data_valid[d_len] = raw_data_valid[d_len].astype(int)
raw_data_test[d_len] = raw_data_test[d_len].astype(int)

In [15]:
counts = raw_data_train[raw_data_train.columns[-1]].value_counts()
counts

0    800
1    800
Name: 1000, dtype: int64

In [16]:
counts = raw_data_valid[raw_data_valid.columns[-1]].value_counts()
counts

0    200
1    200
Name: 1000, dtype: int64

In [17]:
counts = raw_data_test[raw_data_test.columns[-1]].value_counts()
counts

0    2000
1    2000
Name: 1000, dtype: int64

save train/valid/test data and use them for all control experiments

In [18]:
print(f"train_n = {len(raw_data_train)}\nvalid_n = {len(raw_data_valid)}\ntest_n = {len(raw_data_test)}")

train_n = 1600
valid_n = 400
test_n = 4000

In [19]:
# save to csv
fo_dir = case + "/"
raw_data_train.to_csv(fo_dir + 'train.csv', index=False, header=False)
raw_data_valid.to_csv(fo_dir + 'valid.csv', index=False, header=False)
raw_data_test.to_csv(fo_dir + 'test.csv', index=False, header=False)